apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-nhg5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ivcd-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-nhg5@sha256:e21df88dc3c4f906711447afb5a1a1da780e54451e0e0c5827c7f18f45d7d0e9
        name: my-nodejs
        resources: {}
status: {}
